# -*- coding: utf-8 -*-
"""Ahmed hussein.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRNI_ekj4rOBLs3jbVc-06ldbOhfjYeK
"""

item_a = 4
item_b = 6
item_c = 5

budget= 20

total_cost = item_a + item_b + item_c

diff = budget - total_cost


if total_cost < budget:
  print(f"remaining balance= {diff}")

else:
    print ("no remaining balance")